# Generated by Django 6.0.2 on 2026-02-12 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Caisse Principale', max_length=100)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_chantier', models.CharField(choices=[('CONGRES', 'Congrès'), ('FESTIVAL', 'Festival'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('client_nom', models.CharField(max_length=200)),
                ('client_telephone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé'), ('PREVU', 'Prévu')], default='PREVU', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('date_embauche', models.DateField()),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('INTERIM', 'Intérim'), ('STAGE', 'Stage')], max_length=20)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planning', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/')),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_service', models.CharField(choices=[('LOGISTIQUE', 'Logistique'), ('TRANSPORT', 'Transport'), ('AUTRE', 'Autre')], max_length=20)),
                ('tarif_journalier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pourcentage_prime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='AffectationFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours_travailles', models.IntegerField(default=1)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.chantier')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('prime_calculee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.chantier')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.employe')),
            ],
        ),
        migrations.AddField(
            model_name='chantier',
            name='employes',
            field=models.ManyToManyField(through='gestion.AffectationChantier', to='gestion.employe'),
        ),
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_remboursement', models.DateField(blank=True, null=True)),
                ('rembourse', models.BooleanField(default=False)),
                ('motif', models.TextField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.employe')),
            ],
        ),
        migrations.AddField(
            model_name='chantier',
            name='freelancers',
            field=models.ManyToManyField(through='gestion.AffectationFreelancer', to='gestion.freelancer'),
        ),
        migrations.AddField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.poste'),
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_prime', models.DateField(auto_now_add=True)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('description', models.TextField()),
                ('payee', models.BooleanField(default=False)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.chantier')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=20)),
                ('categorie', models.CharField(choices=[('CLIENT', 'Paiement Client'), ('AVANCE', 'Avance sur salaire'), ('PRIME', 'Prime employé'), ('FREELANCE', 'Paiement Freelancer'), ('FOURNITURE', 'Achat fourniture'), ('TRANSPORT', 'Frais transport'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.caisse')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.chantier')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.employe')),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('beneficiaire', models.CharField(max_length=200)),
                ('motif', models.TextField()),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('imprime', models.BooleanField(default=False)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.transaction')),
            ],
        ),
    ]
