# Generated by Django 6.0.2 on 2026-02-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_add_autre_nom_to_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recu',
            name='numero_recu',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
