# Generated by Django 6.0.2 on 2026-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_poste_taux_horaire_alter_recu_numero_recu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='poste',
        ),
        migrations.AddField(
            model_name='employe',
            name='poste_autre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Autre poste (si 'Autre' sélectionné)"),
        ),
        migrations.AddField(
            model_name='employe',
            name='poste_choice',
            field=models.CharField(choices=[('TECHNICIEN', 'Technicien'), ('AUTRE', 'Autre (à préciser)')], default='TECHNICIEN', max_length=20, verbose_name='Poste (choix)'),
        ),
    ]
