# Generated by Django 6.0.2 on 2026-02-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_employe_poste_employe_poste_autre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='poste_autre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autre poste (précisez)'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_choice',
            field=models.CharField(choices=[('TECHNICIEN', 'Technicien'), ('AUTRE', 'Autre (à préciser)')], default='TECHNICIEN', max_length=20, verbose_name='Type de poste'),
        ),
    ]
