# Generated by Django 6.0.2 on 2026-02-13 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_employe_poste_autre_alter_employe_poste_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('date_debut', models.DateField(verbose_name='Date de début de semaine')),
                ('date_fin', models.DateField(verbose_name='Date de fin de semaine')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='gestion.employe')),
            ],
            options={
                'verbose_name': 'Planning horaire',
                'verbose_name_plural': 'Plannings horaires',
                'ordering': ['date_debut', 'jour'],
            },
        ),
    ]
