# Generated by Django 6.0.2 on 2026-02-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_planninghoraire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='planning',
        ),
    ]
