# Generated by Django 4.2.7 on 2026-02-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_planningsimple_delete_planninghoraire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('DANGER', 'Important')], default='INFO', max_length=20)),
                ('categorie', models.CharField(choices=[('EMPLOYE', 'Employé'), ('FREELANCER', 'Freelancer'), ('CHANTIER', 'Chantier'), ('TRANSACTION', 'Transaction'), ('PRIME', 'Prime'), ('PLANNING', 'Planning'), ('SYSTEME', 'Système')], default='SYSTEME', max_length=20)),
                ('lien', models.CharField(blank=True, help_text='Lien vers la ressource concernée', max_length=200, null=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('est_archive', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.chantier')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.employe')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.transaction')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
