# Generated by Django 4.2.7 on 2026-02-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYEE', 'Envoyée'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre')], max_length=20, null=True)),
                ('client_nom', models.CharField(max_length=200)),
                ('client_adresse', models.TextField()),
                ('client_telephone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('societe_nom', models.CharField(default='STAGE PROD', max_length=200)),
                ('societe_adresse', models.TextField(default="123 Rue de l'Entreprise, 75000 Paris")),
                ('societe_telephone', models.CharField(default='01 23 45 67 89', max_length=20)),
                ('societe_email', models.EmailField(default='contact@stageprod.fr', max_length=254)),
                ('societe_siret', models.CharField(default='123 456 789 00012', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(default='Paiement à réception sous 30 jours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='gestion.chantier')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.facture')),
            ],
        ),
    ]
